### ISSUE TITLE
楽天競馬からの過去のレースオッズのスクレイピング(再作成)

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#11]
諸事情( https://twitter.com/poi_kyopro/status/1540288776076873728 )によりissue再作成

----------------------------------

poi-ai commented on 23 Dec 2021
netkeiba、keiba.go、nankankeiba.comなどではしばらくするとオッズデータが削除されるが、楽天競馬では2010年6月1日以降のデータなら単勝〜三連単まで全て残ってるのでそれ以降のデータをぶっこ抜く。地方限定だけど。

----------------------------------

poi-ai commented on 23 Dec 2021 • 
とりあえず単勝複勝ならカラムは、

レース年月日・競馬場コード・レース番号・馬番・オッズ・複オッズ
かな
他は定型じゃないから工夫して抜かんといけんよね

----------------------------------

poi-ai commented on 24 Dec 2021
メモ

https://keiba.rakuten.co.jp/race_card/list/RACEID/ + 年月日 + 競馬場コード(2桁)+ 000000 + レース番号(2桁)

**Comment by poi-ai** [comment]
長い処理になるだろうからtqdm入れたい
先に日数計算して日数分のforでtqdmかな

追)loggerをコンソール出力したらプログレスバーが周回分出るか
loggerをログだけにするか

**Comment by poi-ai** [comment]
7/3高知1R ( https://keiba.rakuten.co.jp/odds/tanfuku/RACEID/202207033129040601 ) でエラー
4頭立て(5頭中1頭取消)で複勝がないため。早めに気づけて良かった。
とりあえずリカバリ処理書く

**Comment by poi-ai** [comment]
2021年8月1日 金沢1Rでエラー

```
2022-07-08 15:30:47,052 - [ERROR] テーブルデータの処理でエラー
2022-07-08 15:30:47,052 - [ERROR] "None of [Index(['馬番', '単勝オッズ'], dtype='object')] are in the [columns]"
2022-07-08 15:30:47,057 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaAI/src/scraping/rakuten.py", line 147, in main
    self.record_odds(race_url, odds_table)
  File "/home/poi/keibaAI/src/scraping/rakuten.py", line 219, in record_odds
    odds = odds_table[0][['馬番', '単勝オッズ']]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['馬番', '単勝オッズ'], dtype='object')] are in the [columns]"
```

原因はコロナ蔓延で取りやめとなったため
https://info.netkeiba.com/?pid=info_detail&id=621

レースが情報がない場合は取得せずにスキップする処理だが、8月1日は出走表まで公開されていてレースがあると勘違いし取得しようとしてエラー

カラムの存在チェックして見つからなければスキップ、がよいかPGに直接日付・競馬場指定で弾くか迷う

-----

前者は、それさえ書いちゃえば同じエラーで止まることはなくなるが、実はレースがあったがフォーマットが変わっていた場合などに気付けない

後者は、同じようなレースがあった場合止まるため逐一弾かなきゃいけないが、リストとして残しとけば、成績取得PGを作る時にそのまま流用できる。

----

んー、前者にしてスキップした場合はログ出力・目視確認が妥当か

**Comment by poi-ai** [comment]
2019年3月19日 佐賀競馬一覧取得でエラー

```
2022-07-14 19:17:52,143 - [INFO] 佐賀競馬場のオッズデータを取得します
2022-07-14 19:17:54,254 - [ERROR] レースURL取得処理でエラー
2022-07-14 19:17:54,254 - [ERROR] list index out of range
2022-07-14 19:17:54,254 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaAI/src/scraping/rakuten.py", line 124, in main
    race_urls = self.get_race_url(baba_url)
  File "/home/poi/keibaAI/src/scraping/rakuten.py", line 188, in get_race_url
    return [link.get('href') for link in race_number[0].find_all('a')]
IndexError: list index out of range
```

今度は、競馬場のレース一覧ページへのリンクはあったが実際はレースがなかったためエラー。
3月28日も同じ状態っぽい。
夜、家に帰ったら直す。

**Comment by poi-ai** [comment]
修正完了

**Comment by poi-ai** [comment]
一通り取得完了。大体丸6日程度かかった。
あとは夜に、データにおかしな点がないかのチェックて問題なければクローズ

**Comment by poi-ai** [comment]
一部余分なデータ( #18 参照)が混ざっていたので、それを除き、年別にCSV分けしたので一通りの作業は終了。クローズ
