### ISSUE TITLE
中央・地方のリアルタイムオッズ処理の合成

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#12]
地方の単複オッズ取得PG( #6 )と中央の単複オッズ取得PG( #9 ) を同時に起動できるような処理修正を行う。

**Comment by poi-ai** [comment]
* 初期処理で対象レースなしの場合にexitしないように
* 対象レースなし or 処理終了となった場合はそれ以降時刻チェック処理を行わないように
* 暫定オッズ取得と確定オッズ取得処理を分けて必ず暫定オッズ取得から行うように
* レース数が増えることを鑑みて、待機時間の調整
* 待機時間チェック処理の中でtime.sleep()を書いているため、返り値で戻して、比較する形で

エラーの場合はexitでもよい…？

**Comment by poi-ai** [comment]
単体で正常稼働するものに手を加えるので、ブランチ切る

**Comment by poi-ai** [comment]
とりあえず実装と簡単な動作確認完了。
明日ローカルかサーバーで回して1日ぶん回して問題なければ閉じる。

**Comment by poi-ai** [comment]
```
        # 発走時刻の切り出し
        for param in self.info_param:
            baba_race_time = []
            soup = self.do_action(param)
            if soup == -1:
                logger.error(f'出馬表一覧の取得に失敗しました')
                raise

            info_table = pd_read.html(str(soup))[0]

            logger.info(f'{babacodechange.jra(param[9:11])}競馬場のレーステーブル取得')

            for i in info_table['発走時刻']:
                m = re.search(r'(\d+)時(\d+)分', i)
                baba_race_time.append(datetime.datetime(int(jst.year()), int(jst.month()), int(jst.day()), int(m.group(1)), int(m.group(2)), 0))

            today_race_time.append(baba_race_time)
```

↑の処理でエラー

```
Traceback (most recent call last):
  File "C:\Users\7096v\Desktop\keibaAI\src\scraping\recordodds.py", line 120, in get_race_info
    self.jra.get_race_info()
  File "C:\Users\7096v\Desktop\keibaAI\src\scraping\jrarecordodds.py", line 186, in get_race_info
    for i in info_table['発走時刻']:
  File "C:\Users\7096v\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\7096v\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: '発走時刻'
```

bf4で取得→HTMLタグからtableタグの箇所を抜き出し→発走時刻の行を抜き出しだけど、行抜き出しでエラー

bf4で失敗したらリトライ処理入るはずなんだけどうまく働いていない？

ちなみに、このエラーの1時間半前から1分前までは発走時刻取得処理はうまく行ってるからURL、PUTパラメータがミスってるとかではない

**Comment by poi-ai** [comment]
挙動テスト用コード

```

import datetime
import pandas as pd
import package
import time
import traceback
import re
import requests
from bs4 import BeautifulSoup
from common import babacodechange, jst, logger, pd_read

logger = logger.Logger()

def do_action(cname, sleep_time = 0, retry_count = 3):
    '''POSTリクエストを送り、HTML情報を受け取る

    Args:
        cname(str):POSTパラメータ

    Returns:
        soup(bs4.BeautifulSoup):受け取ったHTML
    '''
    for _ in range(retry_count):
        try:
            r = requests.post('https://www.jra.go.jp/JRADB/accessO.html', data = {'cname':cname})
            r.encoding = r.apparent_encoding
            soup = BeautifulSoup(r.text, 'lxml')
        except Exception as e:
            logger.error(e)
            logger.error(traceback.format_exc())
            if sleep_time != 0:
                time.sleep(sleep_time)
        else:
            return soup
    else:
        return -1

# 7/3福島2日目出馬表一覧ページのPOSTパラメータ
param = 'pw01drl00032022020220220703/0E'

baba_race_time = []
soup = do_action(param)
if soup == -1:
    logger.error(f'出馬表一覧の取得に失敗しました')
    raise

info_table = pd_read.html(str(soup))[0]

logger.info(f'{babacodechange.jra(param[9:11])}競馬場のレーステーブル取得')

for i in info_table['発走時刻']:
    m = re.search(r'(\d+)時(\d+)分', i)
    baba_race_time.append(datetime.datetime(int(jst.year()), int(jst.month()), int(jst.day()), int(m.group(1)), int(m.group(2)), 0))

print(baba_race_time)
```

成功時
```
[datetime.datetime(2022, 7, 3, 10, 10), datetime.datetime(2022, 7, 3, 10, 45), datetime.datetime(2022, 7, 3, 11, 15), datetime.datetime(2022, 7, 3, 11, 45), datetime.datetime(2022, 7, 3, 12, 35), datetime.datetime(2022, 7, 3, 13, 5), datetime.datetime(2022, 7, 3, 13, 35), datetime.datetime(2022, 7, 3, 14, 5), datetime.datetime(2022, 7, 3, 14, 36), datetime.datetime(2022, 7, 3, 15, 11), datetime.datetime(2022, 7, 3, 15, 45), datetime.datetime(2022, 7, 3, 16, 30)]
```

失敗時(Wi-Fi切断時)
```
(前略)

2022-07-03 23:25:24,477 - [ERROR] 出馬表一覧の取得に失敗しました
Traceback (most recent call last):
  File "C:\Users\7096v\Desktop\keibaAI\src\scraping\main.py", line 45, in <module>
    raise
RuntimeError: No active exception to reraise
```

**Comment by poi-ai** [comment]
前略で割愛してるけど、しっかり3回分リクエスト送って失敗してる記録が出てる。
ログで出たエラーと別なんだよなぁ。

だから、リクエストは通ってなんかの結果は返ってきてるけどその結果が不完全って感じ？
カラムが存在していなかったら`time.sleep()`挟んで取得しなおしかなぁ

というかbs4系の処理全部その可能性がある(リクエスト的には成功だけど結果が不完全)なら根本から見直さなくなきゃいけなくなるかもしれない

**Comment by poi-ai** [comment]
```
2022-07-17 14:06:00,766 - [INFO] 小倉09Rの9分前オッズ取得
2022-07-17 14:06:00,769 - [ERROR] 中央_暫定オッズ取得処理でエラー
2022-07-17 14:06:00,770 - [ERROR] "None of [Index(['馬番', '単勝'], dtype='object')] are in the [columns]"
2022-07-17 14:06:00,770 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaAI/src/scraping/recordodds.py", line 190, in get_select
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['馬番', '単勝'], dtype='object')] are in the [columns]"
```

上と同じで200が返るけど、中身が空っぽだからエラーとなってる。
上でも言ったけど、出るたびに潰さないといけない気がする。別課題で切るかな

**Comment by poi-ai** [comment]
地方競馬(楽天競馬)の方は10日以上エラーなし、中央競馬(JRA)も2日間エラーなしで取得できたのでクローズ
エラーが起こったら別課題を切る

**Comment by poi-ai** [comment]
クローズしてなかったけどエラー起こったからこの課題で直す

```
2022-07-30 09:36:17,618 - [INFO] オッズ記録時間チェック処理開始
2022-07-30 09:36:17,619 - [INFO] 中央：次の記録時間まで102秒
2022-07-30 09:36:17,619 - [INFO] オッズ記録時間チェック処理開始
2022-07-30 09:36:17,621 - [INFO] 地方：次の記録時間まで17502秒
2022-07-30 09:36:17,621 - [INFO] 次の記録時間まで102秒
2022-07-30 09:38:00,797 - [INFO] 札幌01Rの12分前オッズ取得
2022-07-30 09:38:00,883 - [INFO] 帯広ば1Rの302分前オッズ取得
2022-07-30 09:38:00,886 - [ERROR] 地方_暫定オッズ取得処理でエラー
2022-07-30 09:38:00,886 - [ERROR] index 4 is out of bounds for axis 0 with size 1
2022-07-30 09:38:00,886 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/recordodds.py", line 198, in get_select
    self.nar.get_select_realtime()
  File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 260, in get_select_realtime
    self.get_odds(race)
  File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 206, in get_odds
    odds_data = odds_table.loc[:, ['馬番', '単勝オッズ', odds_table.columns[4], odds_table.columns[5]]].replace('-', '', regex = True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index 4 is out of bounds for axis 0 with size 1

2022-07-30 09:38:01,113 - [INFO] オッズデータをCSVへ出力
```

レース5時間前にオッズ取りに行こうとしてるけど、当然まだ公開されてないのでエラー

302分前と出てるから時間取得処理自体は問題なさそう。
取得フラグ管理の箇所かな…？

**Comment by poi-ai** [comment]
昼に中央でエラー

```
2022-07-30 12:44:06,066 - [INFO] オッズ記録時間チェック処理開始
2022-07-30 12:44:06,067 - [INFO] 中央：次の記録時間まで53秒
2022-07-30 12:44:06,067 - [INFO] 地方の取得対象レースはありません
2022-07-30 12:44:06,067 - [INFO] 次の記録時間まで53秒
2022-07-30 12:45:00,277 - [WARNING] オッズ取得処理で正常なデータが取得できませんでした。(1回目)
2022-07-30 12:45:00,277 - [WARNING] 再度オッズ取得処理を実行します。
2022-07-30 12:45:00,438 - [WARNING] オッズ取得処理で正常なデータが取得できませんでした。(2回目)
2022-07-30 12:45:00,438 - [WARNING] 再度オッズ取得処理を実行します。
2022-07-30 12:45:00,596 - [WARNING] オッズ取得処理で正常なデータが取得できませんでした。(3回目)
2022-07-30 12:45:00,596 - [WARNING] 再度オッズ取得処理を実行します。
2022-07-30 12:45:00,756 - [WARNING] オッズ取得処理で正常なデータが取得できませんでした。(4回目)
2022-07-30 12:45:00,756 - [WARNING] 再度オッズ取得処理を実行します。
2022-07-30 12:45:00,968 - [ERROR] オッズ取得処理で5度正常なデータが取得できませんでした
2022-07-30 12:45:00,970 - [ERROR] 中央_暫定オッズ取得処理でエラー
2022-07-30 12:45:00,970 - [ERROR] "None of [Index(['馬番', '単勝'], dtype='object')] are in the [columns]"
2022-07-30 12:45:00,970 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/jrarecordodds.py", line 377, in get_odds
    odds_data = odds_table.loc[:, ['馬番', '単勝']]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1109, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 806, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['馬番', '単勝'], dtype='object')] are in the [columns]"
```

>上と同じで200が返るけど、中身が空っぽだからエラーとなってる。
>上でも言ったけど、出るたびに潰さないといけない気がする。別課題で切るかな
のリカバリ処理で、レスポンスに失敗した場合は5度取得するように処理を直したのに、5回とも失敗するということは別の箇所で問題があるかもしれない。

とりあえず、エラーが出た場合に実際にPOSTレスポンスで取得したHTMLタグと、そのタグの中から抽出したテーブルタグをログに残すような処理を追加して、同じエラーが出た場合に確認できるようにする。

**Comment by poi-ai** [comment]
> クローズしてなかったけどエラー起こったからこの課題で直す
> 
> ```
> 2022-07-30 09:36:17,618 - [INFO] オッズ記録時間チェック処理開始
> 2022-07-30 09:36:17,619 - [INFO] 中央：次の記録時間まで102秒
> 2022-07-30 09:36:17,619 - [INFO] オッズ記録時間チェック処理開始
> 2022-07-30 09:36:17,621 - [INFO] 地方：次の記録時間まで17502秒
> 2022-07-30 09:36:17,621 - [INFO] 次の記録時間まで102秒
> 2022-07-30 09:38:00,797 - [INFO] 札幌01Rの12分前オッズ取得
> 2022-07-30 09:38:00,883 - [INFO] 帯広ば1Rの302分前オッズ取得
> 2022-07-30 09:38:00,886 - [ERROR] 地方_暫定オッズ取得処理でエラー
> 2022-07-30 09:38:00,886 - [ERROR] index 4 is out of bounds for axis 0 with size 1
> 2022-07-30 09:38:00,886 - [ERROR] Traceback (most recent call last):
>   File "/home/poi/keibaai/src/scraping/recordodds.py", line 198, in get_select
>     self.nar.get_select_realtime()
>   File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 260, in get_select_realtime
>     self.get_odds(race)
>   File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 206, in get_odds
>     odds_data = odds_table.loc[:, ['馬番', '単勝オッズ', odds_table.columns[4], odds_table.columns[5]]].replace('-', '', regex = True)
>   File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4604, in __getitem__
>     return getitem(key)
> IndexError: index 4 is out of bounds for axis 0 with size 1
> 
> 2022-07-30 09:38:01,113 - [INFO] オッズデータをCSVへ出力
> ```
> 
> レース5時間前にオッズ取りに行こうとしてるけど、当然まだ公開されてないのでエラー
> 
> 302分前と出てるから時間取得処理自体は問題なさそう。 取得フラグ管理の箇所かな…？



普通にミスっていたわ、直す

**Comment by poi-ai** [comment]
>とりあえず、エラーが出た場合に実際にPOSTレスポンスで取得したHTMLタグと、そのタグの中から抽出したテーブルタグをログに残すような処理を追加して、同じエラーが出た場合に確認できるようにする。

修正、テスト用のデータでは問題なく動作した。実運用ではJRAと同時起動の場合にしか確認できないから来週末までとりあえず保留。

**Comment by poi-ai** [comment]
バグは#24 で修正
それ以外は完了
