### ISSUE TITLE
netkeibaから過去のレースオッズのスクレイピング(中央競馬)

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#16]
過去レースの単勝・複勝オッズ取得をnetkeibaから行えるPGの作成を行う。

#1 と競合しそうなので、うまく分ける

**Comment by poi-ai** [comment]
残タスク
* ログ強化
* エラー時リカバリ処理
* #1 との合成 / 共通処理のクラス化

**Comment by poi-ai** [comment]
2019年10月12日京都5Rのオッズ取得でエラー

```
2022-07-19 12:55:43,917 - [INFO] 2019/10/12のオッズデータの取得を開始します
(中略)
2022-07-19 12:56:06,576 - [INFO] 京都05Rのオッズデータを取得します
2022-07-19 12:56:08,615 - [ERROR] オッズテーブル取得処理でエラー
2022-07-19 12:56:08,615 - [ERROR] string indices must be integers
2022-07-19 12:56:08,615 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/_netkeiba.py", line 125, in main
    odds_table = self.get_odds(race_id)
  File "/home/poi/keibaai/src/scraping/_netkeiba.py", line 203, in get_odds
    df = pd.concat([pd.DataFrame(json_data['data']['odds']['1']).T, pd.DataFrame(json_data['data']['odds']['2']).T], axis = 1)
TypeError: string indices must be integers
```

レース自体は正常に行われ、成立もしているが(取消、除外馬もなし)、なぜかオッズデータがnetkeiba上に存在せず。
このレースのみは、別サイトから引っ張ってくることにする。
存在しない場合のリカバリ処理は今晩実装する。

**Comment by poi-ai** [comment]
2018年12月23日中山3Rも同様のエラー

**Comment by poi-ai** [comment]
‪2013年1月21日中山8R

```
2022-07-21 04:51:47,929 - [INFO] 2013/01/21のオッズデータの取得を開始します
2022-07-21 04:51:50,198 - [INFO] 中山05Rのオッズデータを取得します
2022-07-21 04:51:55,271 - [INFO] 中山06Rのオッズデータを取得します
2022-07-21 04:52:00,349 - [INFO] 中山07Rのオッズデータを取得します
2022-07-21 04:52:05,418 - [INFO] 中山08Rのオッズデータを取得します
2022-07-21 04:52:07,475 - [ERROR] オッズテーブル取得処理でエラー
2022-07-21 04:52:07,475 - [ERROR] All arrays must be of the same length
2022-07-21 04:52:07,475 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/_netkeiba.py", line 125, in main
    odds_table = self.get_odds(race_id)
  File "/home/poi/keibaai/src/scraping/_netkeiba.py", line 210, in get_odds
    df = pd.concat([pd.DataFrame(json_data['data']['odds']['1']).T, pd.DataFrame(json_data['data']['odds']['2']).T], axis = 1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 465, in dict_to_mgr
    arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

なぜかおかしなデータ(-3倍)が一部の馬に付与され、そこに正常なオッズデータがついているデータとついてない馬のデータがあったためDataFrame変換時にカラム数のエラーが出た。

https://race.netkeiba.com/api/api_get_jra_odds.html?type=1&race_id=201306010508

----

あと、この日は1Rから成立したにも関わらずレース一覧には中山1Rから4Rまでの記載がない
https://db.netkeiba.com/race/list/20130121/

----

さらに、1Rから4Rまでの結果画面のオッズと上り3Fが欠損
https://race.netkeiba.com/race/result.html?race_id=201306010501

なんかこの日システムトラブルとかあったんかな

とりあえず、今日の夜直す

**Comment by poi-ai** [comment]
2009年11月29日東京10Rも同一のエラー
追)このレース、ウオッカが勝った年のJCじゃん

**Comment by poi-ai** [comment]
Memo
レスポンスで、**単勝オッズ-3.0**は競走除外で  **-2.0** は出走取消で異常ではない。
雪だか台風で順延となった日は、-3.0がつけられ、後日正式オッズが追加でつけられたからカラム数が増えておかしな値になってたのかも。

**Comment by poi-ai** [comment]
欠損はかなりあるけど、、、
PGの問題ではなく、スクレイピング先に保存されているデータ自体が欠損してるから、どうしようもできないしとりあえずはこれでクローズかなぁ。。。
