### ISSUE TITLE
中央競馬_リアルタイムオッズ取得エラーの修正

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#24]
#12 から引き継ぎ

中央競馬のリアルタイムオッズ取得時に、2週間に1度のペースで起きる下記エラーの修正を行う。

```Traceback (most recent call last):
  File "C:\Users\7096v\Desktop\keibaAI\src\scraping\recordodds.py", line 120, in get_race_info
    self.jra.get_race_info()
  File "C:\Users\7096v\Desktop\keibaAI\src\scraping\jrarecordodds.py", line 186, in get_race_info
    for i in info_table['発走時刻']:
  File "C:\Users\7096v\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\7096v\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: '発走時刻'
```

現状は5度のリトライ処理を追加しても解決できず。

**Comment by poi-ai** [comment]
現時点での修正構想は2点

* エラー発生時に中央全部の処理が止まるのを修正
* 中央→地方の順に処理し、エラー発生した競馬場は地方の後に回すロジックに変更

2点目の修正で治らないなら多分これの対処は無理

**Comment by poi-ai** [comment]
(VPN)cronでエラーが発生したので直後ローカルで実行してみたらエラーが出た。
5分後にエラー吐きそうな部分を全部loggerに出力するように書き換えて実行してみたらエラーを吐かなくなった。
HTTPリクエストは正常扱いになっているが、レスポンスの中身が空
ヘッドレスエラー中とエラー解消後のGUI上での違いはなかった

とりあえず、
* 特定IPによるアクセスブロックではない
* GUI(Google Chrome)での表示は正常
  * ヘッダレスブラウザの一時的なアクセス制限？
  * do_actionのパラメータが変わってる？
    * レスポンスが空なので(パラメータが変わるとパラメータエラーという表示が出るはず)それも違う？

とりあえずdo_actionパラメータとレスポンスコードをログに出力してみる形で来週も様子見。

**Comment by poi-ai** [comment]
とりあえず時刻取得に関しては、5度リトライ処理から更新せずにエラーログだけ出力してスキップという形に修正し、次の周回で取得を行うことにした。
#37 で時刻制限処理も追加したので、数日動きっぱなしとかいうことはなくなると思う。

**Comment by poi-ai** [comment]
とりあえず、さくらのVPSにあげた
明日と週末動かしてみて問題なければクローズ

**Comment by poi-ai** [comment]
問題なく動いたのでクローズ
