### ISSUE TITLE
リアルタイムオッズロジック修正

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#37]
園田7Rが雨の影響で中止となりエラーが起こったため修正を行う。

以下ログ
```
2022-11-23 15:55:02,498 - [INFO] 園田07Rの最終オッズ取得
2022-11-23 15:55:02,501 - [ERROR] 地方_確定オッズ取得処理でエラー
2022-11-23 15:55:02,501 - [ERROR] index 4 is out of bounds for axis 0 with size 1
2022-11-23 15:55:02,501 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/recordodds.py", line 227, in get_select
    self.nar.get_select_confirm()
  File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 278, in get_select_confirm
    self.get_odds(race)
  File "/home/poi/keibaai/src/scraping/narrecordodds.py", line 211, in get_odds
    odds_data = odds_table.loc[:, ['馬番', '単勝オッズ', odds_table.columns[4], odds_table.columns[5]]].replace('-', '', regex = True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index 4 is out of bounds for axis 0 with size 1

2022-11-23 15:55:02,720 - [INFO] 中央・地方競馬オッズ記録システム終了
```

**Comment by poi-ai** [comment]
エラーが出るのはしょうがないしtryでキャッチできてる以上のことはできないから、エラー時にシステム終了してしまうのではなく、該当レースのフラグを完了にして他のレースの取得は続けるように修正する

**Comment by poi-ai** [comment]
とりあえずオッズ取得とCSV出力のエラーに関してはその周回だけ取得/出力しないように修正した
発走時間が取れない場合に関してはエラーが出たら対処を考える
(追)そういえば #24 で発走時刻エラー出てたの忘れてた
