### ISSUE TITLE
#30 のエラー調査・修正

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/keibaAI_disable#44]
#30 関連でエラーが出てるので調査する
```
2022-12-17 10:18:20,542 - [INFO] 2018/03/22のレースデータの取得を開始します
2022-12-17 10:23:34,573 - [ERROR] 園田07R(race_id:201850032207)のレース結果取得処理でエラー
2022-12-17 10:23:34,573 - [ERROR] '5'
2022-12-17 10:23:34,573 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 123, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 530, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '5'
2022-12-17 10:31:34,165 - [INFO] 2018/03/20のレースデータの取得を開始します
2022-12-17 10:33:24,698 - [ERROR] 高知04R(race_id:201854032004)のレース結果取得処理でエラー
2022-12-17 10:33:24,698 - [ERROR] 'NoneType' object has no attribute 'text'
2022-12-17 10:33:24,698 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 123, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 536, in get_result
    rank_table = soup.find('table', class_ = 'RaceCommon_Table Corner_Num').text.split('\n')
AttributeError: 'NoneType' object has no attribute 'text'
2022-12-17 10:33:47,757 - [INFO] 2018/03/19のレースデータの取得を開始します
2022-12-17 10:35:02,770 - [ERROR] 浦和10R(race_id:201842031910)のレース結果取得処理でエラー
2022-12-17 10:35:02,770 - [ERROR] 'NoneType' object has no attribute 'text'
2022-12-17 10:35:02,770 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 123, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 536, in get_result
    rank_table = soup.find('table', class_ = 'RaceCommon_Table Corner_Num').text.split('\n')
AttributeError: 'NoneType' object has no attribute 'text'

2022-12-17 10:35:07,806 - [ERROR] 浦和11R(race_id:201842031911)のレース結果取得処理でエラー
2022-12-17 10:35:07,807 - [ERROR] 'NoneType' object has no attribute 'text'
2022-12-17 10:35:07,807 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 123, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 536, in get_result
    rank_table = soup.find('table', class_ = 'RaceCommon_Table Corner_Num').text.split('\n')
AttributeError: 'NoneType' object has no attribute 'text'

2022-12-17 10:35:12,840 - [ERROR] 浦和12R(race_id:201842031912)のレース結果取得処理でエラー
2022-12-17 10:35:12,840 - [ERROR] 'NoneType' object has no attribute 'text'
2022-12-17 10:35:12,840 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 123, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastnarracedata.py", line 536, in get_result
    rank_table = soup.find('table', class_ = 'RaceCommon_Table Corner_Num').text.split('\n')
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by poi-ai** [comment]
2018/03/22の園田7Rはこっちのソースコードでなくnetkeibaの馬柱・レース結果がおかしい
馬柱→https://nar.netkeiba.com/race/shutuba_past.html?race_id=201850032207&rf=shutuba_submenu
レース結果→https://nar.netkeiba.com/race/result.html?race_id=201850032207&rf=race_submenu
こっちはこちらで対応できるものではないからそのままにする

**Comment by poi-ai** [comment]
他のエラーについては、コーナー通過順テーブルが見つからないことによるエラー。3年半以上遡って初めてこのエラーに遭遇。
このテーブルが見つからない場合は、コーナー通過順カラムは空文字のまま処理を続けるということで。

**Comment by poi-ai** [comment]
修正完了。VPSにマージしたら完了させる

**Comment by poi-ai** [comment]
> 他のエラーについては、コーナー通過順テーブルが見つからないことによるエラー。3年半以上遡って初めてこのエラーに遭遇。 このテーブルが見つからない場合は、コーナー通過順カラムは空文字のまま処理を続けるということで。

2015/12/08以前のすべてのレースでこのエラーが起こるようになってしまい、すべてエラーで取得を行わなくなったため一旦緊急停止。

**Comment by poi-ai** [comment]
とりあえずエラー回避を行うものと、他に見つけていたコードミスを修正してpush。
VPSでも取り込んで3:00からcron。10分くらい様子見て問題なければそのまま走らせる

**Comment by poi-ai** [comment]
朝から中止確定の金沢は発走時刻取得の段階で失敗してる。
その場合の対処も行う

**Comment by poi-ai** [comment]
コーナー通過順テーブルが見つからない場合は、そのカラムを空にして出力する形に修正。
これで問題なく最後まで動いたのでクローズ。
もし#30 で他のバグがあった場合は(既に怪しいところが。。。)別のissueを切ってそちらで対応
